# Generated by Django 2.1.7 on 2019-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifieds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Company_name', models.CharField(max_length=50)),
                ('Contact_details', models.CharField(max_length=550)),
                ('Description', models.CharField(max_length=550)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Event_Date', models.CharField(max_length=50)),
                ('Event_Time', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=550)),
                ('Organizer_details', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Company_name', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=550)),
                ('Email', models.EmailField(max_length=254)),
                ('Other_details', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=550)),
                ('Category', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=550)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
