# Generated by Django 2.1.7 on 2019-02-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
