# Generated by Django 2.1.7 on 2019-02-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190215_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('nonheading', models.CharField(max_length=550)),
            ],
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='Description',
        ),
        migrations.AddField(
            model_name='classifieds',
            name='Description',
            field=models.ManyToManyField(blank=True, to='myapp.NewsDescription'),
        ),
        migrations.AddField(
            model_name='events',
            name='Description',
            field=models.ManyToManyField(blank=True, to='myapp.NewsDescription'),
        ),
        migrations.AddField(
            model_name='news',
            name='Description',
            field=models.ManyToManyField(blank=True, to='myapp.NewsDescription'),
        ),
        migrations.AddField(
            model_name='stories',
            name='Description',
            field=models.ManyToManyField(blank=True, to='myapp.NewsDescription'),
        ),
    ]
