# Generated by Django 2.1.7 on 2019-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190215_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
