# Generated by Django 2.1.7 on 2019-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newsdescription',
            name='heading',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsdescription',
            name='nonheading',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
