# Generated by Django 2.1.7 on 2019-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190215_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Contact_details',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='classifieds',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Event_Date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Event_Time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Organizer_details',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Other_details',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='Title',
        ),
        migrations.AddField(
            model_name='classifieds',
            name='companyName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='contact',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='description',
            field=models.CharField(blank=True, max_length=1550),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classifieds',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=2550),
        ),
        migrations.AddField(
            model_name='events',
            name='from_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='events',
            name='organiserDetails',
            field=models.CharField(blank=True, max_length=1550),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='to_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobs',
            name='otherdetails',
            field=models.CharField(blank=True, max_length=1550),
        ),
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=2550),
        ),
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='stories',
            name='description_heading',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='stories',
            name='description_nonheading',
            field=models.CharField(blank=True, max_length=1550),
        ),
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stories',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='NewsDescription',
        ),
    ]
