# Generated by Django 2.1.7 on 2019-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieds',
            name='contact',
            field=models.TextField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='classifieds',
            name='description',
            field=models.TextField(blank=True, max_length=1550),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, max_length=2550),
        ),
        migrations.AlterField(
            model_name='events',
            name='organiserDetails',
            field=models.TextField(blank=True, max_length=1550),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='otherdetails',
            field=models.TextField(blank=True, max_length=1550),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=2550),
        ),
        migrations.AlterField(
            model_name='stories',
            name='description_heading',
            field=models.TextField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='stories',
            name='description_nonheading',
            field=models.TextField(blank=True, max_length=1550),
        ),
    ]
