# Generated by Django 2.1.7 on 2019-02-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190216_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifieds',
            old_name='description',
            new_name='description_nonheading',
        ),
        migrations.AddField(
            model_name='classifieds',
            name='description_heading',
            field=models.TextField(blank=True, max_length=550),
        ),
    ]
